// <auto-generated />
using System;
using CoreTestApp.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreTestApp.Persistance.Migrations
{
    [DbContext(typeof(CoreTestAppContext))]
    [Migration("20191127114415_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreTestApp.Persistance.Models.Broadcast", b =>
                {
                    b.Property<Guid>("BroadcastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BroadcastTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FirstOnline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BroadcastId");

                    b.HasIndex("BroadcastTypeId");

                    b.ToTable("Broadcast","test");
                });

            modelBuilder.Entity("CoreTestApp.Persistance.Models.BroadcastType", b =>
                {
                    b.Property<Guid>("BroadcastTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BroadcastTypeId");

                    b.ToTable("BroadcastType","test");

                    b.HasData(
                        new
                        {
                            BroadcastTypeId = new Guid("0151059b-a859-4931-f3f2-08d773208df1"),
                            Name = "Basketball"
                        });
                });

            modelBuilder.Entity("CoreTestApp.Persistance.Models.Broadcast", b =>
                {
                    b.HasOne("CoreTestApp.Persistance.Models.BroadcastType", "BroadcastType")
                        .WithMany()
                        .HasForeignKey("BroadcastTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
